alerting:
  alertmanagers:
  - static_configs:
    - targets: null
global:
  evaluation_interval: 60s
  scrape_interval: 10s
rule_files: null
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - "localhost:9090"
- job_name: samm
  honor_labels: true
  static_configs:
  - targets:
    - "exporter:5000"

